"""Command-line generator for construction streams, with a live status log.

Examples
--------
    python -m backend.cli --n 17 --validate
    python -m backend.cli --primes --validate
    python -m backend.cli --range 3 60 --validate

Every run emits a flushed, timestamped status log to stdout *and* to
``data/generate.log`` (START / per-n progress / DONE), so a long generation can be
watched with ``tail -f data/generate.log`` and is never an opaque black box.
"""

from __future__ import annotations

import argparse
import time
from datetime import datetime

from . import cache
from .constructible import FERMAT_PRIME_SET
from .construct import build, validate_doc

LOG_PATH = cache.REPO_ROOT / "data" / "generate.log"

# Fermat primes generated by default; 65537 is excluded (its stream is huge and slow).
DEFAULT_PRIMES = (3, 5, 17, 257)


def _log(msg: str) -> None:
    """Print and append one timestamped, flushed status line."""
    line = f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {msg}"
    print(line, flush=True)
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(line + "\n")


def _targets(args: argparse.Namespace) -> list[int]:
    if args.n is not None:
        return [args.n]
    if args.primes:
        return list(DEFAULT_PRIMES)
    if args.range is not None:
        lo, hi = args.range
        return list(range(lo, hi + 1))
    raise SystemExit("specify one of --n, --primes, or --range")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate regular n-gon construction streams.")
    parser.add_argument("--n", type=int, help="a single n")
    parser.add_argument("--range", type=int, nargs=2, metavar=("LO", "HI"),
                        help="inclusive range of n")
    parser.add_argument("--primes", action="store_true",
                        help=f"generate the Fermat primes {DEFAULT_PRIMES}")
    parser.add_argument("--validate", action="store_true",
                        help="check generated vertices against exp(2*pi*i*k/n)")
    parser.add_argument("--force", action="store_true",
                        help="regenerate even if a cache file exists")
    parser.add_argument("--no-save", action="store_true", help="do not write cache files")
    args = parser.parse_args(argv)

    targets = _targets(args)
    t0 = time.perf_counter()
    _log(f"START generation: {len(targets)} target(s) {targets[:8]}"
         f"{'...' if len(targets) > 8 else ''} | validate={args.validate} force={args.force}")

    n_built = n_skipped = n_unsupported = n_nonconstructible = 0
    worst_err = 0.0
    for i, n in enumerate(targets, 1):
        if not args.force and not args.no_save and cache.load(n) is not None:
            n_skipped += 1
            _log(f"[{i}/{len(targets)}] n={n}: cached, skip")
            continue
        ts = time.perf_counter()
        doc = build(n)
        if not doc.get("constructible"):
            n_nonconstructible += 1
            status = "NOT constructible"
        elif not doc.get("supported"):
            n_unsupported += 1
            status = "constructible (stream pending milestone)"
        else:
            n_built += 1
            status = f"{len(doc['commands'])} commands"
            if args.validate:
                ok, err = validate_doc(doc)
                worst_err = max(worst_err, err)
                status += f", validate {'OK' if ok else 'FAIL'} (max_err={err:.2e})"
                if not ok:
                    _log(f"[{i}/{len(targets)}] n={n}: VALIDATION FAILED err={err:.2e}")
        # Persist only the Fermat-prime building blocks; other n are built on demand
        # and cached client-side (browser).  Non-primes are still built & validated here.
        path = None
        if not args.no_save and doc.get("constructible") and n in FERMAT_PRIME_SET:
            path = cache.save(doc)
        _log(f"[{i}/{len(targets)}] n={n}: {status} "
             f"[{time.perf_counter() - ts:.2f}s]{' -> ' + str(path) if path else ''}")

    _log(f"DONE: built={n_built} skipped={n_skipped} unsupported={n_unsupported} "
         f"nonconstructible={n_nonconstructible} worst_err={worst_err:.2e} "
         f"elapsed={time.perf_counter() - t0:.2f}s | cache={cache.COMMANDS_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
